### ISSUE TITLE
Bender.yml do not work

### ISSUE THREAD

**Issue by jonathan2503** [pulp-platform/hwpe-mac-engine#5]
Hello to everyone,
i'm trying to install this directory to see how works the HWPE.
This are the step:

$ git clone --recursive https://github.com/pulp-platform/hwpe-mac-engine 

$ cd hwpe-mac-engine/

$  make checkout
make: ***  Nessuna regola per generare l'obiettivo «checkout».  Arresto.

Any suggestion?
thanks in advance

**Comment by FrancescoConti** [comment]
This is not a standalone environment but an IP. You can check out https://github.com/pulp-platform/hwpe-tb for a testbench
