### ISSUE TITLE
Alternative Simulator Options for Running Tests Without QuestaSim

### ISSUE THREAD

**Issue by zealshah29** [pulp-platform/hwpe-mac-engine#6]
Hey everyone,

I'm currently facing a challenge as I don't have access to QuestaSim for running tests. Are there any alternative simulators that can serve the same purpose? If so, could you please suggest some options? Additionally, any guidance on how to integrate these alternative simulators into my workflow would be immensely helpful.

Thanks!

**Comment by FrancescoConti** [comment]
Currently we only support QuestaSim. It is definitely possible, but not effortless, to make this work in Verilator (some syntax, such as wide use of interfaces, could be a bit difficult to chew for the tool).

Here https://github.com/pulp-platform/hwpe-tb/tree/master you can find some partial / incomplete  support for Verilator (look in `hw/veri`), which I never had time to finish. In case you want to take a look (and maybe contribute?) feel free! :)

**Comment by FrancescoConti** [comment]
You can also find very extensive doc on how to use Verilator in other PULP IPs developed more recently, such as Cheshire https://github.com/pulp-platform/cheshire

**Comment by zealshah29** [comment]
Okay, thank you!
